// <auto-generated />
using System;
using Billar306.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Billar306.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524171418_AddLiquidacion")]
    partial class AddLiquidacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("Billar306.API.Models.Anticipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForzadoPorJefe")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioAutorizanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioAutorizanteId");

                    b.ToTable("Anticipos");
                });

            modelBuilder.Entity("Billar306.API.Models.ClienteFrecuente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientesFrecuentes");
                });

            modelBuilder.Entity("Billar306.API.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("ConfiguracionSistema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "LimiteAnticipoPorc",
                            Descripcion = "Porcentaje máximo de anticipo sobre sueldo",
                            Valor = "40"
                        },
                        new
                        {
                            Id = 2,
                            Clave = "MontoMaxGravedadBaja",
                            Descripcion = "Diferencia de caja máxima para gravedad baja",
                            Valor = "2000"
                        },
                        new
                        {
                            Id = 3,
                            Clave = "PeriodoRedondeo",
                            Descripcion = "Días del período de redondeo a favor del cliente",
                            Valor = "30"
                        },
                        new
                        {
                            Id = 4,
                            Clave = "PausaMinimaJuegoMin",
                            Descripcion = "Minutos mínimos entre sesiones de juego del mismo empleado",
                            Valor = "30"
                        },
                        new
                        {
                            Id = 5,
                            Clave = "ModalidadJuego",
                            Descripcion = "Modalidad de juego: tiempo | consumicion | ambas",
                            Valor = "consumicion"
                        },
                        new
                        {
                            Id = 6,
                            Clave = "DuracionTokenHoras",
                            Descripcion = "Horas de validez del token JWT",
                            Valor = "8"
                        },
                        new
                        {
                            Id = 7,
                            Clave = "TarifaHoraEmpleado",
                            Descripcion = "Tarifa por hora para empleados",
                            Valor = "0"
                        },
                        new
                        {
                            Id = 8,
                            Clave = "TarifaHoraEncargado",
                            Descripcion = "Tarifa por hora para encargados",
                            Valor = "0"
                        });
                });

            modelBuilder.Entity("Billar306.API.Models.ConsumicionMesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemConfiteriaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("SesionMesaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemConfiteriaId");

                    b.HasIndex("SesionMesaId");

                    b.ToTable("ConsumicionesMesa");
                });

            modelBuilder.Entity("Billar306.API.Models.EventoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravedad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotaRevision")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revisado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioRevisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EventosTurno");
                });

            modelBuilder.Entity("Billar306.API.Models.Fiado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteFrecuenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionPrenda")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SesionMesaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFrecuenteId");

                    b.HasIndex("SesionMesaId")
                        .IsUnique();

                    b.HasIndex("UsuarioRegistroId");

                    b.ToTable("Fiados");
                });

            modelBuilder.Entity("Billar306.API.Models.IngresoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemConfiteriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemConfiteriaId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("IngresosStock");
                });

            modelBuilder.Entity("Billar306.API.Models.ItemConfiteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockApertura")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemsConfiteria");
                });

            modelBuilder.Entity("Billar306.API.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Libre",
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Libre",
                            Numero = 2
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Libre",
                            Numero = 3
                        },
                        new
                        {
                            Id = 4,
                            Estado = "Libre",
                            Numero = 4
                        },
                        new
                        {
                            Id = 5,
                            Estado = "Libre",
                            Numero = 5
                        },
                        new
                        {
                            Id = 6,
                            Estado = "Libre",
                            Numero = 6
                        },
                        new
                        {
                            Id = 7,
                            Estado = "Libre",
                            Numero = 7
                        },
                        new
                        {
                            Id = 8,
                            Estado = "Libre",
                            Numero = 8
                        });
                });

            modelBuilder.Entity("Billar306.API.Models.RegistroHoraEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HorasTrabajadas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosHora");
                });

            modelBuilder.Entity("Billar306.API.Models.SesionMesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteFrecuenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("MesaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MontoRecibido")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalCobrado")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Vuelto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFrecuenteId");

                    b.HasIndex("MesaId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesMesa");
                });

            modelBuilder.Entity("Billar306.API.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AperturaCompleta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DiferenciaCaja")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EfectivoConfiteria")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EfectivoMaquinas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<string>("GravedadDiferencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoAperturaCaja")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoCierreFisico")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoEsperado")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotaCierre")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Billar306.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SueldoBase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Administrador",
                            NombreUsuario = "jefe",
                            PasswordHash = "$2a$11$NWBTmNk2n4iuWLxlOZW5r.4Kh7IqFJSaKfxtYCmdcYVQsj7l479pO",
                            Rol = "jefe",
                            SueldoBase = 0m
                        });
                });

            modelBuilder.Entity("Billar306.API.Models.Anticipo", b =>
                {
                    b.HasOne("Billar306.API.Models.Usuario", "Empleado")
                        .WithMany("Anticipos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Turno", "Turno")
                        .WithMany("Anticipos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Usuario", "UsuarioAutorizante")
                        .WithMany()
                        .HasForeignKey("UsuarioAutorizanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Turno");

                    b.Navigation("UsuarioAutorizante");
                });

            modelBuilder.Entity("Billar306.API.Models.ConsumicionMesa", b =>
                {
                    b.HasOne("Billar306.API.Models.ItemConfiteria", "ItemConfiteria")
                        .WithMany("Consumiciones")
                        .HasForeignKey("ItemConfiteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.SesionMesa", "SesionMesa")
                        .WithMany("Consumiciones")
                        .HasForeignKey("SesionMesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemConfiteria");

                    b.Navigation("SesionMesa");
                });

            modelBuilder.Entity("Billar306.API.Models.EventoTurno", b =>
                {
                    b.HasOne("Billar306.API.Models.Turno", "Turno")
                        .WithMany("Eventos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Billar306.API.Models.Fiado", b =>
                {
                    b.HasOne("Billar306.API.Models.ClienteFrecuente", "ClienteFrecuente")
                        .WithMany("Fiados")
                        .HasForeignKey("ClienteFrecuenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.SesionMesa", "SesionMesa")
                        .WithOne("Fiado")
                        .HasForeignKey("Billar306.API.Models.Fiado", "SesionMesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteFrecuente");

                    b.Navigation("SesionMesa");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("Billar306.API.Models.IngresoStock", b =>
                {
                    b.HasOne("Billar306.API.Models.ItemConfiteria", "ItemConfiteria")
                        .WithMany()
                        .HasForeignKey("ItemConfiteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemConfiteria");

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Billar306.API.Models.RegistroHoraEmpleado", b =>
                {
                    b.HasOne("Billar306.API.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Billar306.API.Models.SesionMesa", b =>
                {
                    b.HasOne("Billar306.API.Models.ClienteFrecuente", "ClienteFrecuente")
                        .WithMany("Sesiones")
                        .HasForeignKey("ClienteFrecuenteId");

                    b.HasOne("Billar306.API.Models.Mesa", "Mesa")
                        .WithMany("Sesiones")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Turno", "Turno")
                        .WithMany("Sesiones")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteFrecuente");

                    b.Navigation("Mesa");

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Billar306.API.Models.Turno", b =>
                {
                    b.HasOne("Billar306.API.Models.Usuario", "Usuario")
                        .WithMany("Turnos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Billar306.API.Models.ClienteFrecuente", b =>
                {
                    b.Navigation("Fiados");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Billar306.API.Models.ItemConfiteria", b =>
                {
                    b.Navigation("Consumiciones");
                });

            modelBuilder.Entity("Billar306.API.Models.Mesa", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Billar306.API.Models.SesionMesa", b =>
                {
                    b.Navigation("Consumiciones");

                    b.Navigation("Fiado");
                });

            modelBuilder.Entity("Billar306.API.Models.Turno", b =>
                {
                    b.Navigation("Anticipos");

                    b.Navigation("Eventos");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Billar306.API.Models.Usuario", b =>
                {
                    b.Navigation("Anticipos");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
