// <auto-generated />
using System;
using Billar306.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Billar306.Persistencia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720210558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("Billar306.Dominio.Models.Clientes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreditoHabilitado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoCredito")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Clientes.CobroDeuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PrendaId");

                    b.ToTable("CobrosDeudas", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Clientes.Prenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuentaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionPrenda")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoResponsableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<double>("MontoPrenda")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CuentaId")
                        .IsUnique();

                    b.HasIndex("EmpleadoResponsableId");

                    b.ToTable("Prendas", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catalogos", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("ConfiguracionesSistema", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.IngresoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("IngresosStock", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.ItemIngresoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("IngresoStockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngresoStockId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsIngresoStock", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Empleado.Amonestacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duracion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gravedad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Amonestaciones", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Empleado.Anticipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForzadoPorJefe")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioAutorizanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioAutorizanteId");

                    b.ToTable("Anticipos", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Empleado.RegistroTurnoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Comisiones")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Descuentos")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HorasTrabajadas")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Limpieza")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("RegistrosTurnoEmpleado", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Operatividad.DiaLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaCerrado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiasLaborales", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Operatividad.EventoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRevisado")
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreEvento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotaRevision")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revisado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioRevisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioRevisionId");

                    b.ToTable("EventosTurno", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Operatividad.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuxiliarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaLaboralId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Diferencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("GravedadDiferencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MontoContado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoEsperado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotaCierre")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitularId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalConfiteria")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalDeuda")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalMaquinas")
                        .IsRequired()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalMesas")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuxiliarId");

                    b.HasIndex("DiaLaboralId");

                    b.HasIndex("TitularId");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.CuentaBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoAperturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmpleadoCierreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VentaConfiteriaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoAperturaId");

                    b.HasIndex("EmpleadoCierreId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("VentaConfiteriaId")
                        .IsUnique();

                    b.ToTable("Cuentas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.ItemConfiteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VentaConfiteriaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaConfiteriaId");

                    b.ToTable("ItemsConfiteria", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Maquina.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaOcupada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identificador")
                        .IsUnique();

                    b.ToTable("Maquinas", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Maquina.TransaccionMaquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsIngreso")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SesionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SesionId");

                    b.ToTable("TransaccionesMaquina", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Mesas.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ocupada")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Mesas", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CuentaBaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuentaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Metodo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PagoParcial")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CuentaBaseId");

                    b.HasIndex("CuentaId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.VentaConfiteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VentasConfiteria", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Maquina.SesionMaquina", b =>
                {
                    b.HasBaseType("Billar306.Dominio.Models.Venta.CuentaBase");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalEgresos")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalIngresos")
                        .HasColumnType("TEXT");

                    b.HasIndex("MaquinaId");

                    b.ToTable("SesionesMaquina", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Mesas.SesionMesa", b =>
                {
                    b.HasBaseType("Billar306.Dominio.Models.Venta.CuentaBase");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("MesaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoSesionMesa")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasIndex("MesaId");

                    b.ToTable("SesionesMesa", (string)null);
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Clientes.CobroDeuda", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Clientes.Prenda", "Prenda")
                        .WithMany("Abonos")
                        .HasForeignKey("PrendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Clientes.Prenda", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Venta.CuentaBase", "Cuenta")
                        .WithOne("PrendaGenerada")
                        .HasForeignKey("Billar306.Dominio.Models.Clientes.Prenda", "CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "EmpleadoResponsable")
                        .WithMany()
                        .HasForeignKey("EmpleadoResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Cuenta");

                    b.Navigation("EmpleadoResponsable");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.IngresoStock", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Operatividad.Turno", "TurnoEmpleado")
                        .WithMany("IngresosStock")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("TurnoEmpleado");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.ItemIngresoStock", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.IngresoStock", "IngresoStock")
                        .WithMany("Productos")
                        .HasForeignKey("IngresoStockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Control.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngresoStock");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.Producto", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Catalogo", "Catalogo")
                        .WithMany("Productos")
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalogo");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Empleado.Amonestacion", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "Empleado")
                        .WithMany("Amonestaciones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Empleado.Anticipo", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "Empleado")
                        .WithMany("Anticipos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Operatividad.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "UsuarioAutorizante")
                        .WithMany()
                        .HasForeignKey("UsuarioAutorizanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Turno");

                    b.Navigation("UsuarioAutorizante");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Empleado.RegistroTurnoEmpleado", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Operatividad.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Operatividad.EventoTurno", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Operatividad.Turno", "Turno")
                        .WithMany("Eventos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "UsuarioRevision")
                        .WithMany()
                        .HasForeignKey("UsuarioRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Turno");

                    b.Navigation("UsuarioRevision");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Operatividad.Turno", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "Auxiliar")
                        .WithMany()
                        .HasForeignKey("AuxiliarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Billar306.Dominio.Models.Operatividad.DiaLaboral", "DiaLaboral")
                        .WithMany("Turnos")
                        .HasForeignKey("DiaLaboralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "Titular")
                        .WithMany("Turnos")
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auxiliar");

                    b.Navigation("DiaLaboral");

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.CuentaBase", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "EmpleadoApertura")
                        .WithMany()
                        .HasForeignKey("EmpleadoAperturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Control.Usuario", "EmpleadoCierre")
                        .WithMany()
                        .HasForeignKey("EmpleadoCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Billar306.Dominio.Models.Operatividad.Turno", "Turno")
                        .WithMany("CuentasAbiertas")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Venta.VentaConfiteria", "Confiteria")
                        .WithOne("CuentaAsociada")
                        .HasForeignKey("Billar306.Dominio.Models.Venta.CuentaBase", "VentaConfiteriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Confiteria");

                    b.Navigation("EmpleadoApertura");

                    b.Navigation("EmpleadoCierre");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.ItemConfiteria", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Control.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Venta.VentaConfiteria", "Venta")
                        .WithMany("ItemsConfiterias")
                        .HasForeignKey("VentaConfiteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Maquina.TransaccionMaquina", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Venta.Maquina.SesionMaquina", "Sesion")
                        .WithMany("Transacciones")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Pago", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Venta.CuentaBase", null)
                        .WithMany("Pagos")
                        .HasForeignKey("CuentaBaseId");

                    b.HasOne("Billar306.Dominio.Models.Venta.CuentaBase", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Maquina.SesionMaquina", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Venta.CuentaBase", null)
                        .WithOne()
                        .HasForeignKey("Billar306.Dominio.Models.Venta.Maquina.SesionMaquina", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Venta.Maquina.Maquina", "Maquina")
                        .WithMany("Sesiones")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Mesas.SesionMesa", b =>
                {
                    b.HasOne("Billar306.Dominio.Models.Venta.CuentaBase", null)
                        .WithOne()
                        .HasForeignKey("Billar306.Dominio.Models.Venta.Mesas.SesionMesa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billar306.Dominio.Models.Venta.Mesas.Mesa", "Mesa")
                        .WithMany("Sesiones")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Clientes.Prenda", b =>
                {
                    b.Navigation("Abonos");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.Catalogo", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.IngresoStock", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Control.Usuario", b =>
                {
                    b.Navigation("Amonestaciones");

                    b.Navigation("Anticipos");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Operatividad.DiaLaboral", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Operatividad.Turno", b =>
                {
                    b.Navigation("CuentasAbiertas");

                    b.Navigation("Eventos");

                    b.Navigation("IngresosStock");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.CuentaBase", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("PrendaGenerada");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Maquina.Maquina", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Mesas.Mesa", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.VentaConfiteria", b =>
                {
                    b.Navigation("CuentaAsociada");

                    b.Navigation("ItemsConfiterias");
                });

            modelBuilder.Entity("Billar306.Dominio.Models.Venta.Maquina.SesionMaquina", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
